### ISSUE TITLE
does not generate files

### ISSUE THREAD

**Issue by ignatandrei** [byme8/DuckInterface#1]
Hello
I am trying to provide a repo with all interesting Roslyn Source Code Generators examples
I found your very interesting and I have tried to make an example
Unfortunately, it does not generate any files. 
Could you see why  ? 

The example is at https://github.com/ignatandrei/RSCG_Examples/tree/main/Later_DuckTyping/src/DucKing

**Comment by byme8** [comment]
Looks like, fail is related to the fact that you split the declarations between multiple projects. I will look at it.

**Comment by byme8** [comment]
@ignatandrei Seems like I modern C# it is not possible to make it work between multiple projects at the same time. The partial class has to be defined in one assembly, the inheritance will not do a trick because the implicit operator works only for the type where it is declared. So, you can try to define everything in one assembly. In this case, it will definitely work.

**Comment by ignatandrei** [comment]
Let's suppose I want to make an interface for FileSystem ( defined by Microsoft). I define an interface, IFileSystem. Could I use your nuget for duck typing FileSystem to IFileSystem?

**Comment by byme8** [comment]
Yes, you can but with some limitations. Here is an example:
``` cs 
[Duckable]
interface IStream
{
    int ReadByte();
}

public class Program
{
    public static void Main()
    {
        var stream = new MemoryStream();
        Do(stream);
    }

    static void Do(DIStream stream)
    {

    }
}
```
Such source code will work but only within one assembly where duckable interface is defined. This limitation exists because partial classes can't be implemented in different assemblies.

P.S. I fixed a bunch of bugs and published a new NuGet. So, use DuckInterface 0.1.5

**Comment by ignatandrei** [comment]
I have updated and still does not generate code. I understand ( partially) the idea of same assembly.

Could you look at https://github.com/ignatandrei/RSCG_Examples/tree/main/Later_DuckTyping/src/DucKing and suggest how to modify code that works  ? ( However, I do not want ALL in one project - the console app should be separated from the BL )

**Comment by byme8** [comment]
@ignatandrei As I said, the duckable interface has to be defined in the same assembly where it is used.

Here is the fixed example: https://github.com/byme8/RSCG_Examples/commit/956976180e218698c11c72c8cd94a962af614878

**Comment by byme8** [comment]
In my example, the BL project is separate from the console project, but the interfaces project has to go away. It is close to the golang mindset I would say. Where the interfaces are defined in the place where you expect to use them. It implies the there would be multiple small interfaces that doing the same thing.

**Comment by byme8** [comment]
Also, I want to clarify one thing. It is a 'just for fun' project and it has some limitations that just make it impossible to use it in production in current form.

**Comment by ignatandrei** [comment]
Thanks.

**Comment by ignatandrei** [comment]
I do agree with you . I will mention , however, here: https://github.com/ignatandrei/RSCG_Examples.
This code is number 39

**Comment by byme8** [comment]
@ignatandrei If you are looking for stuff that can be used in production you can have a look at https://github.com/byme8/ZeroIoC. It is an IoC container that generates mappings between the interface and implementation at compile-time via SourceGenerator.

Also, I am working on https://github.com/byme8/Apparatus.AOT.Reflection. It is a fast reflection via source generators. it is still in active development, but there is some stuff that you can have a look at.

**Comment by ignatandrei** [comment]
Thank you very much. I will look at it.
